server:
  port: 8091

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27018/
      database: ShopLyXRPayment

    redis:
      host: localhost
      port: 6379
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  mail:
    host: smtp.gmail.com
    port: 587
    username: phanly10102003@gmail.com
    password: xmqy ayig pfuv xucl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          debug: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

api:
  prefix: api/v1

jwt:
  expiration: 86400
  secretKey: AJE9z3rCRKipY9Ce1BNmZZUa81JiZpeYtm/CxZOwYLU=
